name: polymer_elements
version: 0.2.0-pre.7
authors:
- Erik Grimes <erik.grimes@gmail.com>
- Günter Zöchbauer <guenter@gzoechbauer.com>
description: >
  A Dart port of polymer-elements
  (https://github.com/Polymer/polymer-elements).
homepage: https://github.com/ErikGrimes/polymer_elements
documentation: http://erikgrimes.github.io/polymer_elements/docs/index.html
environment:
  sdk: ">=1.3.0 <2.0.0"
dependencies:
  polymer: ">=0.10.0-pre.10 <1.0.0"
  polymer_ui_elements: #0.2.0-pre.7
    git: https://github.com/ErikGrimes/polymer_ui_elements
#    path: ../polymer_ui_elements

dev_dependencies:
  unittest:  ">=0.10.1+2 <1.0.0"

transformers:
- polymer:
    entry_points:

